### ISSUE TITLE
Set up the plugin to work on the mobile app

### ISSUE THREAD

**Issue by odeialba** [odeialba/moodle-mod_sortvoting#26]

**Comment by odeialba** [comment]
Fixed on https://github.com/odeialba/moodle-mod_sortvoting/pull/52

**Comment by odeialba** [comment]
I'm reopening this issue since it does not work on IPhone

**Comment by davefoord** [comment]
It appeared to work on my iPhone when I tested it - what isn't working?

**Comment by odeialba** [comment]
@davefoord Sorry, it turns out that there is no error. A tester reported a bug to me that thought it was IOS related. It turns out that it is this bug that I am still not able to replicate: https://github.com/odeialba/moodle-mod_sortvoting/issues/63
