### ISSUE TITLE
Change behaviour so once the student has voted, they are taken automatically to the results screen

### ISSUE THREAD

**Issue by davefoord** [odeialba/moodle-mod_sortvoting#60]
At the moment the students have to click on the 'responses' option within the menu bar at top to see the responses, this isn't obvious and especially on a small screen where this items disappears into the hamburger icon - is easily missed. Could it be changed so that if the item is set to allow students to see the results, when they save their response it automatically takes them to the results page (this is what the choice activity does).

**Comment by odeialba** [comment]
Hello @davefoord
Thank you for creating this issue and I am sorry for the delay of working on it. I created a PR with the fix and it will soon be merged: https://github.com/odeialba/moodle-mod_sortvoting/pull/70
