### ISSUE TITLE
Make the cards stand out more from the background

### ISSUE THREAD

**Issue by davefoord** [odeialba/moodle-mod_sortvoting#62]
Is it worth making the draggable cards slightly more distinct - I have done this by adding some CSS to give the cards a thin grey border, but not everyone will have the ability or know-how to do this.

This was the CSS that I personally added to my site:

/*Adds a border around the cards in the preference sorting activity*/
li.d-flex.card.p-3.mb-2.optionitem.draggable {
    border-style: solid;
    border-color: #c0c0c0;
    border-width: thin;
}

**Comment by odeialba** [comment]
Hello @davefoord 
Thank you for creating this issue and I am sorry for the delay of working on it. I created a PR with the fix and it will soon be merged: https://github.com/odeialba/moodle-mod_sortvoting/pull/68
