### ISSUE TITLE
Sorting cards not picking up filters (e.g. mlang filters)

### ISSUE THREAD

**Issue by davefoord** [odeialba/moodle-mod_sortvoting#73]
At the moment, if I try to use the mlang filters as per https://moodle.org/plugins/filter_multilang2 these are not respected within the cards.

Could this be changed so that text filters also work within the cards - it would be really useful if they do.

**Comment by odeialba** [comment]
Hello @davefoord 
Thank you for reporting this. That's a really good suggestion. I'll have it in mind for the next version

**Comment by odeialba** [comment]
Will be fixed in https://github.com/odeialba/moodle-mod_sortvoting/pull/75

**Comment by odeialba** [comment]
@davefoord This fix was added to the latest release. Sorry for the delay.
